# Generated by Django 3.2.3 on 2021-06-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloglistmdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='bloglist',
        ),
    ]
